version: '3.7'
services:
    postgres1:
        image: postgres:12.2-alpine
        environment:
            POSTGRES_USER: postgres
            POSTGRES_DB: postgres
            POSTGRES_PASSWORD: password
        command: >
            postgres
              -c wal_level=replica
              -c max_wal_senders=2
              -c wal_keep_segments=100
              -c hot_standby=on
              -c ssl=on
              -c ssl_cert_file=/etc/certs/server.crt
              -c ssl_key_file=/etc/certs/server.key
              -c hba_file=/etc/postgres/pg_hba.conf
        volumes:
        - ./volumes/postgres1/:/var/lib/postgresql/data/
        - ./certs/:/etc/certs/
        - ./pg_hba.conf:/etc/postgres/pg_hba.conf

    postgres2:
        image: postgres:12.2-alpine
        environment:
            POSTGRES_USER: postgres
            POSTGRES_DB: postgres
            POSTGRES_PASSWORD: password
        command: >
            postgres
              -c ssl=on
              -c ssl_cert_file=/etc/certs/server.crt
              -c ssl_key_file=/etc/certs/server.key
              -c hba_file=/etc/postgres/pg_hba.conf
        volumes:
        - ./volumes/postgres2/:/var/lib/postgresql/data/
        - ./certs/:/etc/certs/
        - ./pg_hba.conf:/etc/postgres/pg_hba.conf
